Organizations:

  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: ../crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "ANY OrdererMSP.members"
      Writers:
        Type: Signature
        Rule: "ANY OrdererMSP.members"
      Admins:
        Type: Signature
        Rule: "ANY OrdererMSP.admins"

  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: ../crypto-config/peerOrganizations/org1.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "ANY Org1MSP.members"
      Writers:
        Type: Signature
        Rule: "ANY Org1MSP.members"
      Admins:
        Type: Signature
        Rule: "ANY Org1MSP.admins"
      Endorsement:
        Type: Signature
        Rule: "ANY Org1MSP.peers"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 10485760
    PreferredMaxBytes: 2097152
  Organizations:
    - *OrdererOrg
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ApplicationCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:

  GenesisProfile:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1

  ChannelProfile:
    <<: *ChannelDefaults
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
